version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data  
    networks:
      - app-network

  dashboard:
    build:
      context: .
      dockerfile: dashboard/Dockerfile
    ports:
      - "8501:8501"
    networks:
      - app-network

  sensor1:
    image: abelfodil/sensor:0.0.1
    depends_on:
      - app
    environment:
      - SERVER_URL=http://app:8080/receive
      - SCENARIO_ID=1
    networks:
      - app-network

  sensor2:
    image: abelfodil/sensor:0.0.1
    depends_on:
      - app
    environment:
      - SERVER_URL=http://app:8080/receive
      - SCENARIO_ID=2
    networks:
      - app-network

  sensor3:
    image: abelfodil/sensor:0.0.1
    depends_on:
      - app
    environment:
      - SERVER_URL=http://app:8080/receive
      - SCENARIO_ID=3
    networks:
      - app-network

  sensor4:
    image: abelfodil/sensor:0.0.1
    depends_on:
      - app
    environment:
      - SERVER_URL=http://app:8080/receive
      - SCENARIO_ID=4
    networks:
      - app-network

  sensor5:
    image: abelfodil/sensor:0.0.1
    depends_on:
      - app
    environment:
      - SERVER_URL=http://app:8080/receive
      - SCENARIO_ID=5
    networks:
      - app-network

  sensor6:
    image: abelfodil/sensor:0.0.1
    depends_on:
      - app
    environment:
      - SERVER_URL=http://app:8080/receive
      - SCENARIO_ID=6
    networks:
      - app-network

  sensor7:
    image: abelfodil/sensor:0.0.1
    depends_on:
      - app
    environment:
      - SERVER_URL=http://app:8080/receive
      - SCENARIO_ID=7
    networks:
      - app-network

  sensor8:
    image: abelfodil/sensor:0.0.1
    depends_on:
      - app
    environment:
      - SERVER_URL=http://app:8080/receive
      - SCENARIO_ID=8
    networks:
      - app-network

  sensorCustom:
    image: abelfodil/sensor:0.0.1
    depends_on:
      - app
    environment:
      - SERVER_URL=http://app:8080/receive
      - PLANT_ID=12
      - SENSOR_ID=88712531
      - SENSOR_VERSION=FR-v7
      - PERIOD=2s
      - MEASURES=temperature:285.15°K,temperature:286.15°K,humidity:12%
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
