apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensorcustom-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensorcustom
  template:
    metadata:
      labels:
        app: sensorcustom
    spec:
      containers:
      - name: sensorcustom
        image: abelfodil/sensor:0.0.1
        env:
        - name: SERVER_URL
          value: "http://app-service:8080/receive"
        - name: PLANT_ID
          value: "12"
        - name: SENSOR_ID
          value: "88712531"
        - name: SENSOR_VERSION
          value: "FR-v7"
        - name: PERIOD
          value: "2s"
        - name: MEASURES
          value: "temperature:285.15°K,temperature:286.15°K,humidity:12%"
