apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor6-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor6
  template:
    metadata:
      labels:
        app: sensor6
    spec:
      containers:
      - name: sensor6
        image: abelfodil/sensor:0.0.1
        env:
        - name: SERVER_URL
          value: "http://flask-service:8080/receive"
        - name: SCENARIO_ID
          value: "6"
