apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor7-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor7
  template:
    metadata:
      labels:
        app: sensor7
    spec:
      containers:
      - name: sensor7
        image: abelfodil/sensor:0.0.1
        env:
        - name: SERVER_URL
          value: "http://app-service:8080/receive"
        - name: SCENARIO_ID
          value: "7"
